### ISSUE TITLE
a question about updating centroids

### ISSUE THREAD

**Issue by CrisisLee** [clara-labs/spherecluster#7]
hi ~ I have a question about updating centroids in your code as follows:
```
        # computation of the means
        if sp.issparse(X):
            centers = _k_means._centers_sparse(X, labels, n_clusters,
                                               distances)
        else:
            centers = _k_means._centers_dense(X, labels, n_clusters, distances)

        # l2-normalize centers (this is the main contibution here)
        centers = normalize(centers)
```
When using cosine similarity in clustering, if you just normalize the centers calculated  with _k_means._centers_XXX, which were designed to update centers when using eu distance, won't the result centers have different directions from what they should be?
Hope I've describe my question clearly and looking forward to your reply~ Thanks~

**Comment by jasonlaska** [comment]
This was meant to only be used with euclidean distance (I suppose the option to use a different metric is one of the pitfalls of only patching on a change to sklearn's existing kmeans utility).

I'm not sure that normalizing will change directions (as we are just scaling by positive scalars), can you provide an example? Its possible that the directions of the cluster centers obtained using cosine-similarity vs. euclidean will have the opposite directions (for the same initialization) due to the relationship below.

Cosine similarity has a 1-1 relationship to the euclidean dist when the the vectors are unit-normalized (https://en.wikipedia.org/wiki/Cosine_similarity#Properties):

![image](https://user-images.githubusercontent.com/1652668/41108078-7d0a77ca-6a28-11e8-89c1-07552832bde8.png)

Hopefully that helps!

**Comment by CrisisLee** [comment]
Thanks a lot for answering me, and sorry I didn't describe my question properly. 
When we calculate the center of A, B and C in fig 1 with euclidean distance, the result will be D. So after L2 normalization, the new center will be point B. However, when we calculate center of A and B first, the result will be E and after calculating center of E and C, the result will be somewhere like F.  What's more, when calculating B and C first, the result will be different from F. 
On the other hand, when A, B and C are points in fig 2, the center will be O, and how can we normalize it(although it can hardly happen)?
So what do you think about this issue?
Thanks again for answering~
![wechatimg2](https://user-images.githubusercontent.com/6140044/41447034-c5951e7e-7085-11e8-9798-726cc3d1d33f.jpeg)

**Comment by jasonlaska** [comment]
**Regarding Figure 1**
I believe that your geometry is basically correct so perhaps I can clarify how the algorithm is setup to reduce confusion.

A key part of k-means and its variants is picking the parameter `k`, the number of clusters _a priori_.  The algorithm repeats in two phases from there:
- assign each data point to a cluster center
- recompute cluster centers based on data-points with the same cluster assignment

In your first calculation that inspects the center of **A**, **B**, **C** (resulting initially in roughly D which normalizes to roughly B) there is an implicit assumption that `k=1` or that we are only evaluating one set of points that are all assigned to the same cluster (e.g., say the first iteration of k-means with random cluster assignments, `k > 1` but we're just examining one of the assignment sets).  In the case where `k = 1`, we're done the cluster center becomes **B**, which seems like a reasonable point on the circle to me.  In the other case, we still obtain **B** as a cluster center, however in the _next iteration_ of the algorithm, its unlikely that **C** will be assigned to this cluster center because it is likely closer to a different center due to its location.

In your second calculation that inspects the center of **A** and **B**  (resulting in **E**after normalization), the key point is that normalization will not happen _before_ averaging in **C**.  It is true that if you normalize before averaging in **C**, the result will be different (this is because `a/b + c/d ~= (a + b) / (c+d)`. So either in this scenario `k > 1` and **C** is not included in this cluster assignment, or if **C** is included then it will only ever be averaged in before normalization as in your first calculation.  Either way, `normalize(normalize(A + B) + C)` and `normalize(normalize(B + C) + A)` will not happen in the algorithm.  


**Regarding Figure 2**
Yes, it seems this can happen in the following cases:
- `k = 1` and all points are organized as you depict; however, if you only care about finding the center of all points, you may want to handle this computation manually and handle this edge case.

- `k >1` and an initialization of cluster assignments gets unlucky (unlikely but possible); assuming the first pass of the algorithm succeeds, it doesn't seem to me that this case can happen when `k > 1` in subsequent iterations.  k-means is often initialized by random cluster assignments which could introduce this edge case, with low probability (requires both at least one subset of the data to have 0-mean and for the random cluster assignment to choose that subset);  increase `k` will lower this probability. Since k-means is often run multiple times and the best result is chosen, one could handle an exception cause by normalizing by zero, if it did come up.  I think by default we use [k-means++](https://en.wikipedia.org/wiki/K-means%2B%2B) to initialize this algorithm which tried to spread out the cluster centers (in euclidean space), which should also reduce the likelihood of this case from happening.
